language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyourideas-nodejs-jm
  api_key:
    secure: f3hjz4A5FahprbM4L63Qsl9W/XCieN1KWrQ7RIDrogYbjhhf2G5PVooiLSrGQvtGFRwZHhdLc3h8VST7AcOZqMDgW6g2ItGPini6GRBXYeGZ3aoBYi0E+QiW8bFfm6+3mKlBAntNy4B0e0nyzN//ynbKh/shwqRtuh3O+eglasmAnzYyX52I5J3OXJa67w6Qgp7o9gEA6KK5e+c6Cl4JlNgPV+WlAaofHYmv4eSHIqjSePh+f+BiB6yAJ8zO/VidIPx4yrda8nKxJeGLDFWAWhVIzRyixrZldh0F3AhxbqDxFRSvWG2Z6OfGoCDmvSFariLl0kzzZXBAsQRQF69BaEX4kiYyhc5kji2D68pFVrPeoZ611/aIHUCF3PdDGQms4lsBdy9/JgBcrvHsE6BvwctJeVOXAN4IyAzZHjwd1JbqyvexHC67ZRlPkZycBRUzlDC8DK3jtQzXCabzCaaOpOGJj7yt9PNqHAEBy++VQT4GRiVQJuQM4rxkIS8FE1wtlCcUHZ/w5E0dQGKXaZCpabNyXf8fU9ueyzH7WE4QMJFTvLS0FIqEH9dQ+3mFEyNGW6BpURvqE4Uw7FfWUK1Aq097A/f5+lJvkiHdHReRT3Puigm8hF69F8iCzZDAfgc77a8eJgIR0/LCm4r/WtYVSmHYxbFOQMMnPV/gs5TUBSY=
